2020-08-05 11:41:40,105 ERROR: Exception on / [GET] [in /Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/aleksandar-h/Development/GitHub/blog/app/main/routes.py", line 57, in index
    return render_template(
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/aleksandar-h/Development/GitHub/blog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/aleksandar-h/Development/GitHub/blog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/aleksandar-h/Development/GitHub/blog/app/templates/base.html", line 47, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/aleksandar-h/Development/GitHub/blog/app/templates/index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "/Users/aleksandar-h/Development/GitHub/blog/app/templates/_post.html", line 10, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2020-08-05 11:44:24,512 INFO: Microblog startup [in /Users/aleksandar-h/Development/GitHub/blog/app/__init__.py:80]
2020-08-05 11:44:29,862 ERROR: Exception on /explore [GET] [in /Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aleksandar-h/Development/GitHub/blog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/aleksandar-h/Development/GitHub/blog/app/main/routes.py", line 72, in explore
    page, app.config["POSTS_PER_PAGE"], False
NameError: name 'app' is not defined
